version: 'foxnet-0.1.{build}'

# we compile every commit under all branches
#branch:
# only:
#  - main

# only run CI if we changed actual code
only_commits:
  files:
    - src/
    - include/
    - examples/
    - CMakeLists.txt
    - appveyor.yml

# images we're using
image:
  - Ubuntu2004
  - Visual Studio 2019

platform:
  - x64

for:
-
  matrix:
    only:
      - image: Ubuntu2004
  install:
    - sudo apt install clang cmake -y
  build_script:
    - sh: cmake -B build && cd build && make -j
  artifacts:
    - path: bin
      name: ubuntu20_04-bin-x64
      type: zip
-
  matrix:
    only:
      - image: Visual Studio 2019
  build_script:
    - ps: |
        # "Debug" builds are disabled, since we don't really need them
        $configurations = "Release"

        # AppVeyor uses VS2019 Community
        $vsPath = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"

        Import-Module "$vsPath\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
        Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation

        if (Test-Path -LiteralPath "build") {
            Remove-Item "build" -Recurse
            Write-Output "Deleted existing build folder"
        }

        Invoke-Expression "cmake -B build"
        if ($LASTEXITCODE -ne "0") {
            Write-Error "cmake generation failed!" -ErrorAction Stop
        }
        Write-Output "Generated build files"

        foreach ($configuration in $configurations) {
            Write-Output "Building $configuration"

            # try build, if error ocurred exit out
            Invoke-Expression "msbuild build\FoxNet.sln /maxcpucount:4 /p:BuildInParallel=true /p:CL_MPCount=4 /p:UseMultiToolTask=true /p:Configuration=$configuration"
            if ($LASTEXITCODE -ne "0") {
                Write-Error "msbuild build failed for $configuration!" -ErrorAction Stop
            }

            Write-Output "Built $configuration"
        }
  artifacts:
    - path: bin
      name: windows-vs2019-bin-x64
      type: zip