version: 'foxnet-0.1.{build}'

# we compile every commit under all branches
#branch:
# only:
#  - main

# only run CI if we changed actual code
only_commits:
  files:
    - src/
    - include/
    - examples/
    - CMakeLists.txt
    - appveyor.yml

# images we're using
image:
  - Ubuntu2004

platform:
  - x64

install:
  - sudo apt install clang cmake -y

build_script:
  - mkdir build && cd build && cmake ../ . && make -j

artifacts:
  - path: bin
    name: ubuntu20_04-bin-x64
    type: zip