name: Check Builds

on:
  push:
    paths:
        - examples/**
        - src/**
        - include/**
        - .github/workflows/check-build.yaml

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install clang cmake -y
      - name: Create CMake build files
        run: cmake -B build
      - name: Check compilation
        run: cmake --build build --config Release
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: foxnet-binaries-ubuntu
          path: bin

  windows-build:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Create CMake build files
        run: cmake -B build
      - name: Check compilation
        run: cmake --build build --config Release
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: foxnet-binaries-windows
          path: bin

  macOS-build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Create CMake build files
      run: cmake -B build
    - name: Check compilation
      run: cmake --build build
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: foxnet-binaries-macos
        path: bin